[colors]
  # Default colors
  [colors.primary]
  background = '0x1e2127'
  foreground = '0xabb2bf'
  bright_foreground = '0xe6efff'
  
  # cursor colors
  [colors.cursor]
  text = '0x000000'
  cursor = '0xffffff'

  # Normal colors
  [colors.normal]
  black = '0x1e2127'
  red = '0xe06c75'
  green = '0x98c379'
  yellow = '0xd19a66'
  blue = '0x61afef'
  magenta = '0xc678dd'
  cyan = '0x56b6c2'
  white = '0x828791'

  # Bright colors
  [colors.bright]
  black = '0x5c6370'
  red = '0xe06c75'
  green = '0x98c379'
  yellow = '0xd19a66'
  blue = '0x61afef'
  magenta = '0xc678dd'
  cyan = '0x56b6c2'
  white = '0xe6efff'

  # Dim colors
  [colors.dim]
  black = '0x1e2127'
  red = '0xe06c75'
  green = '0x98c379'
  yellow = '0xd19a66'
  blue = '0x61afef'
  magenta = '0xc678dd'
  cyan = '0x56b6c2'
  white = '0x828791'

  # Indexed Colors
  # [colors.indexed_colors]
  # [[colors.indexed_colors]]
  # index = 16
  # color = '0x000000'
